version: '3.8'

services:
  app:
    build: .
    volumes:
      - node_modules:/root/node_modules
      - .:/spa
  root:
    build: ./root
    command:  bash -c "npm start"
    environment:
      - CORSHEADER="http://localhost:9000"
      - PROXY=true
    ports:
      - 9000:9000
    volumes:
      - node_modules:/root/node_modules
      - .:/root
  navbar:
    build: ./navbar
    command:  bash -c "npm start"
    environment:
      - CORSHEADER="http://localhost:8500"
      - PROXY=true
    ports:
      - 8500:8080
    volumes:
      - node_modules:/navbar/node_modules
      - .:/app
  login:
    build: ./login
    command:  bash -c "npm start"
    environment:
      - CORSHEADER="http://localhost:3033"
      - PROXY=true
    ports:
      - 3033:8080
    volumes:
      - node_modules:/login/node_modules
      - .:/login
volumes:
  node_modules: